export interface Dex {
  name: DexName;
  chainId: string;
  type: DexType;
  properties: Record<string, any>;
  logoURI: string;
}

// identifiers for dexes
export enum DexName {
  AGNI_V3 = "Agni V3",
  AERODROME_SOLIDLY = "Aerodrome Solidly",
  AERODROME_V3 = "Aerodrome V3",
  APESWAP_V2 = "Apeswap V2",
  APESWAP_V3 = "Apeswap V3",
  ASTROPORT = "Astroport",
  BALANCER_V2 = "Balancer V2",
  BASESWAP_V2 = "Baseswap V2",
  BASESWAP_V3 = "Baseswap V3",
  BEAMSWAP_V2 = "Beamswap V2",
  BEAMSWAP_V3 = "Beamswap V3",
  BEAMSWAP_SADDLE = "Beamswap Saddle",
  BEETS_V2 = "Beets V2",
  CAMELOT_V2 = "Camelot V2",
  CAMELOT_V3 = "Camelot V3",
  CURVE_V2 = "Curve V2",
  ELLIPSIS = "Ellipsis",
  EQUILIBRE = "Equilibre",
  EQUALIZER = "Equalizer",
  ETHEREX_V3 = "Etherex V3",
  FRAXSWAP_V2 = "Fraxswap V2",
  FUSIONX_V2 = "FusionX V2",
  FUSIONX_V3 = "FusionX V3",
  GLIQUID_V4 = "Gliquid V4",
  GMX = "GMX",
  HONEYSWAP_V2 = "Honeyswap V2",
  HORIZON_V2 = "Horizon V2",
  HORIZON_V3 = "Horizon V3",
  HYBRA_V2 = "Hybra V2",
  HYBRA_V3 = "Hybra V3",
  HYPERSWAP_V2 = "Hyperswap V2",
  HYPERSWAP_V3 = "Hyperswap V3",
  KYBERSWAP = "KyberSwap",
  KYBERSWAP_AGGREGATOR = "kyberswap Aggregator",
  KYO_V2 = "Kyo V2",
  KYO_V3 = "Kyo V3",
  KINETIX_V3 = "Kinetix V3",
  KITTENSWAP_V2 = "Kittenswap V2",
  KITTENSWAP_V3 = "Kittenswap V3",
  KODIAK_V3 = "Kodiak V3",
  LAMINAR_V3 = "Laminar V3",
  LYNEX_V3 = "Lynex V3",
  MACHINE_X_V3 = "MachineX V3",
  MENTO_V2 = "Mento V2",
  MOAI_V3 = "Moai V3",
  NILE_SOLIDLY = "Nile Solidly",
  NILE_V3 = "Nile V3",
  OKU_V2 = "Oku V2",
  OPENOCEAN = "OpenOcean",
  OSMOSIS = "Osmosis",
  OKU_V3 = "Oku V3",
  PANCAKESWAP_V2 = "Pancakeswap V2",
  PANCAKESWAP_V3 = "Pancakeswap V3",
  PANCAKESWAP_STABLE = "Pancakeswap Stable",
  PANGOLIN_V2 = "Pangolin V2",
  PHARAOH_SOLIDLY = "Pharaoh Solidly",
  PHARAOH_V3 = "Pharaoh V3",
  PLATYPUS = "Platypus",
  PRINTR = "Printr",
  PROJECT_X_V3 = "Project X V3",
  QUICKSWAP_V2 = "Quickswap V2",
  QUICKSWAP_V3 = "Quickswap V3",
  RAMSES_SOLIDLY = "Ramses Solidly",
  RA_V3 = "Ra V3",
  RAMSES_V3 = "Ramses V3",
  SHADOW_V2 = "Shadow V2",
  SHADOW_V3 = "Shadow V3",
  SONEX_V3 = "Sonex V3",
  SPOOKYSWAP_V2 = "Spookyswap V2",
  STELLASWAP_V2 = "Stellaswap V2",
  STELLASWAP_V3 = "Stellaswap V3",
  STELLASWAP_V4 = "Stellaswap V4",
  STELLASWAP_SADDLE = "Stellaswap Saddle",
  SURGE_V3 = "Surge V3",
  SUSHISWAP_V2 = "Sushiswap V2",
  SUSHISWAP_V3 = "Sushiswap V3",
  SWAPBASED_V2 = "Swapbased V2",
  SYNTHSWAP_V2 = "SynthSwap V2",
  SYNTHSWAP_V3 = "SynthSwap V3",
  SKYDROME = "Skydrome",
  SWAPR_V3 = "Swapr V3",
  THENA_SOLIDLY = "Thena Solidly",
  THENA_V3 = "Thena V3",
  TRADERJOE_V2 = "Trader Joe V2",
  TRADERJOE_V21 = "Trader Joe V2.1",
  TRADERJOE_V22 = "Trader Joe V2.2",
  TRIDENT = "Trident",
  THRUSTER_V3 = "Thruster V3",
  THRUSTER_V2 = "Thruster V2",
  UBESWAP_V2 = "Ubeswap V2",
  UBESWAP_V3 = "Ubeswap V3",
  UNISWAP_V2 = "Uniswap V2",
  UNISWAP_V3 = "Uniswap V3",
  WAGMI_V3 = "Wagmi V3",
  WIGOSWAP_V2 = "Wigoswap V2",
  WOMBAT = "Wombat",
  VELODROME_SOLIDLY = "Velodrome Solidly",
  VELODROME_V2 = "Velodrome V2",
  VELODROME_V3 = "Velodrome V3",
  VELOCIMETER = "Velocimeter",
  ZYBERSWAP_V2 = "Zyberswap V2",
  ZYBERSWAP_V3 = "Zyberswap V3",  
}

// identifiers dex adapters
export enum DexType {
  // EVM
  ALGEBRA = "algebra",
  ALGEBRA_V4 = "algebra-v4",
  BALANCER_V2 = "balancer-v2",
  CURVE = "curve",
  GMX = "gmx",
  KYBERSWAP_ELASTIC = "kyberswap-elastic",
  PLATYPUS = "platypus",
  PANCAKESWAP_STABLE = "pancakeswap-stable",
  PRINTR = "printr",
  SADDLE = "saddle",
  SLIPSTREAM = "slipstream",
  SOLIDLY = "solidly",
  TRADERJOE_V21 = "traderjoe-v21",
  TRADERJOE_V22 = "traderjoe-v22",
  TRIDENT = "trident",
  WOMBAT = "wombat",
  UNISWAP_V2 = "uniswap-v2",
  UNISWAP_V3 = "uniswap-v3",
  MENTO_V2 = "mento-v2",
  // COSMOS
  OSMOSIS = "osmosis",
  ASTROPORT = "astroport",

  // ONCE WE START ADDING DEXES WE WILL BE MOVING THEM ABOVE
  /*
  DUALITY = "Duality",
  */
}
