export interface Dex {
  name: DexName;
  chainId: string;
  type: DexType;
  properties: Record<string, any>;
}

// identifiers for dexes
export enum DexIcon {
  AGNI_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/agni.svg",
  AERODROME = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/aerodrome.svg",
  APESWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/apeswap.png",
  APESWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/apeswap.png",
  BALANCER_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/balancer.svg",
  BASESWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/baseswap.png",
  BASESWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/baseswap.png",
  BEAMSWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/beamswap.svg",
  CAMELOT = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/camelot.svg",
  CURVE_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/curve.svg",
  ELLIPSIS = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/ellipsis.svg",
  EQUILIBRE = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/equilibre.svg",
  EQUALIZER = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/equalizer.svg",
  FUSIONX_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/fusionx.png",
  FUSIONX_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/fusionx.png",
  GMX = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/gmx.svg",
  HORIZON = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/horizon.svg",
  HORIZON_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/horizon.svg",
  KYBERSWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/kyberswap.svg",
  KYBERSWAP_AGGREGATOR = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/kyberswap.svg",
  KINETIX_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/kinetix.svg",
  MENTO_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/mento.svg",
  OPENOCEAN = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/openocean.svg",
  OSMOSIS = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/osmosis.svg",
  PANCAKESWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/pancakeswap.svg",
  PANCAKESWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/pancakeswap.svg",
  PANCAKESWAP_STABLE = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/pancakeswap.svg",
  PANGOLIN = "tps://raw.githubusercontent.com/0xsquid/assets/main/images/providers/pangolin.svg",
  PLATYPUS = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/platypus.png",
  QUICKSWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/quickswap.svg",
  QUICKSWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/quickswap.svg",
  RAMSES = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/ramses.svg",
  SPOOKYSWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/spookyswap.svg",
  STELLASWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/stellaswap.svg",
  STELLASWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/stellaswap.svg",
  STELLASWAP_SADDLE = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/stellaswap.svg",
  SUSHISWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/sushi.svg",
  SUSHISWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/sushi.svg",
  SWAPBASED = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/swapbased.png",
  SYNTHSWAP_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/synthswap.svg",
  SYNTHSWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/synthswap.svg",
  SKYDROME = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/skydrome.png",
  THENA = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/thena.svg",
  THENA_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/thena.svg",
  TRADERJOE = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/traderjoe.svg",
  TRIDENT = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/sushi.svg",
  UBESWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/ubeswap.svg",
  UBESWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/ubeswap.svg",
  UNISWAP_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/uniswap.svg",
  UNISWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/uniswap.svg",
  WOMBAT = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/wombat.svg",
  VELODROME = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/velodrome.svg",
  VELODROME_V2 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/velodrome.svg",
  VELOCIMETER = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/velocimeter.png",
  ZYBERSWAP = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/zyberswap.svg",
  ZYBERSWAP_V3 = "https://raw.githubusercontent.com/0xsquid/assets/main/images/providers/zyberswap.svg",
}

export enum DexName {
  AGNI_V3 = "Agni V3",
  AERODROME = "Aerodrome",
  APESWAP = "ApeSwap V2",
  APESWAP_V3 = "ApeSwap V3",
  BALANCER_V2 = "Balancer V2",
  BASESWAP = "BaseSwap V2",
  BASESWAP_V3 = "BaseSwap V3",
  BEAMSWAP = "Beamswap V2",
  CAMELOT = "Camelot V3",
  CURVE_V2 = "Curve V2",
  ELLIPSIS = "Ellipsis",
  EQUILIBRE = "Equilibre",
  EQUALIZER = "Equalizer",
  FUSIONX_V2 = "FusionX V2",
  FUSIONX_V3 = "FusionX V3",
  GMX = "GMX",
  HORIZON = "Horizon",
  HORIZON_V3 = "Horizon V3",
  KYBERSWAP = "KyberSwap Elastic",
  KYBERSWAP_AGGREGATOR = "KybersSwap Aggregator",
  KINETIX_V3 = "Kinetix V3",
  MENTO_V2 = "Mento V2",
  OPENOCEAN = "OpenOcean",
  OSMOSIS = "Osmosis",
  PANCAKESWAP = "PancakeSwap",
  PANCAKESWAP_V3 = "PancakeSwap V3",
  PANCAKESWAP_STABLE = "PancakeSwap Stable",
  PANGOLIN = "Pangolin",
  PLATYPUS = "Platypus",
  QUICKSWAP = "Quickswap",
  QUICKSWAP_V3 = "Quickswap V3",
  RAMSES = "Ramses",
  SPOOKYSWAP = "SpookySwap",
  STELLASWAP = "StellaSwap",
  STELLASWAP_V3 = "Stellaswap V3",
  STELLASWAP_SADDLE = "StellaSwap Saddle",
  SUSHISWAP = "Sushi V2",
  SUSHISWAP_V3 = "Sushi V3",
  SWAPBASED = "SwapBased",
  SYNTHSWAP_V2 = "SynthSwap V2",
  SYNTHSWAP_V3 = "SynthSwap V3",
  SKYDROME = "Skydrome",
  THENA = "Thena",
  THENA_V3 = "Thena V3",
  TRADERJOE = "Trader Joe V1",
  TRIDENT = "Trident",
  UBESWAP = "UbeSwap V2",
  UBESWAP_V3 = "UbeSwap V3",
  UNISWAP_V2 = "Uniswap V2",
  UNISWAP_V3 = "Uniswap V3",
  WOMBAT = "Wombat",
  VELODROME = "Velodrome",
  VELODROME_V2 = "Velodrome V2",
  VELOCIMETER = "Velocimeter",
  ZYBERSWAP = "ZyberSwap V2",
  ZYBERSWAP_V3 = "ZyberSwap V3",
}

// identifiers dex adapters
export enum DexType {
  // EVM
  ALGEBRA = "algebra",
  BALANCER_V2 = "balancer-v2",
  CURVE = "curve",
  GMX = "gmx",
  KYBERSWAP_ELASTIC = "kyberswap-elastic",
  PLATYPUS = "platypus",
  PANCAKESWAP_STABLE = "pancakeswap-stable",
  SADDLE = "saddle",
  SOLIDLY = "solidly",
  TRIDENT = "trident",
  WOMBAT = "wombat",
  UNISWAP_V2 = "uniswap-v2",
  UNISWAP_V3 = "uniswap-v3",
  MENTO_V2 = "mento-v2",
  
  
  // COSMOS
  OSMOSIS = "osmosis",

  // ONCE WE START ADDING DEXES WE WILL BE MOVING THEM ABOVE
  /*
  DUALITY = "Duality",
  */
}
