name: Linter and build

on:
  push:
  pull_request:
    types: [ready_for_review, synchronize, opened]
    branches: ["main", "develop"]

jobs:
  api:
    name: Types validation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        name: Use Node.js 18.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Run linter
        run: |
          yarn lint
